"""Audit layer: shared risk management and account guards."""

from audit.risk_manager import (
    AccountState,
    CHALLENGE_BASE_RISK_PCT_MAX,
    CHALLENGE_BASE_RISK_PCT_MIN,
    CHALLENGE_PROFIT_TARGET_PCT,
    FUNDED_BASE_RISK_PCT,
    LOT_FACTOR_FLOOR,
    MAX_DAILY_EXPOSURE_LIMIT_PCT,
    PROFILE_BAYES_ALLOW,
    PROFILE_L2_MIN_SCORE,
    PROFILE_LLM_CAUTION_MULT,
    PropFirmProfile,
    apply_daily_dd_brake,
    apply_lot_factor_floor,
    calc_position_size,
    challenge_profit_progress_pct,
    compute_l45_multipliers,
    compute_trade_risk_pct,
    effective_base_risk_pct,
    lot_from_risk_budget,
    multiplier_bayes,
    multiplier_candidate,
    multiplier_daily_dd,
    multiplier_dd,
    multiplier_llm,
    multiplier_streak,
    normalize_profile,
)

from audit.l2_threshold_manager import (
    l2_reject_reason_tags,
    resolve_l2_min_candidate_score,
    verify_l2_rules,
)

__all__ = [
    "AccountState",
    "CHALLENGE_BASE_RISK_PCT_MAX",
    "CHALLENGE_BASE_RISK_PCT_MIN",
    "CHALLENGE_PROFIT_TARGET_PCT",
    "FUNDED_BASE_RISK_PCT",
    "LOT_FACTOR_FLOOR",
    "MAX_DAILY_EXPOSURE_LIMIT_PCT",
    "PROFILE_BAYES_ALLOW",
    "PROFILE_L2_MIN_SCORE",
    "PROFILE_LLM_CAUTION_MULT",
    "PropFirmProfile",
    "apply_daily_dd_brake",
    "apply_lot_factor_floor",
    "calc_position_size",
    "challenge_profit_progress_pct",
    "compute_l45_multipliers",
    "compute_trade_risk_pct",
    "effective_base_risk_pct",
    "lot_from_risk_budget",
    "multiplier_bayes",
    "multiplier_candidate",
    "multiplier_daily_dd",
    "multiplier_dd",
    "multiplier_llm",
    "multiplier_streak",
    "normalize_profile",
    "l2_reject_reason_tags",
    "resolve_l2_min_candidate_score",
    "verify_l2_rules",
]
