"""Lifecycle stage constants and allocation rules."""
from __future__ import annotations

STAGE_INCUBATION = "INCUBATION"
STAGE_CANDIDATE = "CANDIDATE"
STAGE_PRODUCTION = "PRODUCTION"
STAGE_CORE = "CORE"
STAGE_RECOVERY = "RECOVERY"
STAGE_RETIRED = "RETIRED"

ALL_STAGES = (
    STAGE_INCUBATION,
    STAGE_CANDIDATE,
    STAGE_PRODUCTION,
    STAGE_CORE,
    STAGE_RECOVERY,
    STAGE_RETIRED,
)

CORE_MIN_ALLOCATION = 0.10

STAGE_ALLOCATION: dict[str, float | None] = {
    STAGE_INCUBATION: 0.0,
    STAGE_CANDIDATE: 0.05,
    STAGE_PRODUCTION: None,
    STAGE_CORE: None,
    STAGE_RECOVERY: 0.05,
    STAGE_RETIRED: 0.0,
}

PAAE_ELIGIBLE_STAGES = {STAGE_PRODUCTION, STAGE_CORE}
